ExpressFunc:
  component: '@serverless/tencent-express'
  inputs:
    functionName: express-function
    region: ap-guangzhou
    code: ./
    exclude:
      - .env
    apigatewayConf:
      protocols:
        - http
        - https
      environment: test
